# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='user_id',
            new_name='user',
        ),
    ]
