# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_auto_20170124_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
